### ISSUE TITLE
About this project

### ISSUE THREAD

**Issue by StephS** [HorstBaerbel/GBA-mem#1]
Hey, I found this thinking the same thing, and it looks like you're the only one who has tried this.
But I see your warning, and the short table that seems to state that none of the memory worked.
Any idea what went wrong?

**Comment by HorstBaerbel** [comment]
The GBA started the test ROM for a couple of seconds, but then died. I think the power supply was not sufficient for the chip I used (IS62WV12816BLL). I unsoldered the chip and the GBA starts and boots due to IWRAM being available, but when loading ROMs it crashes obviously. I haven't found the time to try soldering the old RAM chip again or trying out the IS62WV12816EBLLs I have lying around here.
There's a [GBA PCB / circuit redesign](https://github.com/Zekfoo/AGZ) that would be perfect for trying this out as the power supply should be much more capable.

**Comment by HorstBaerbel** [comment]
You can also find me on [discord/gbadev](https://discord.io/gbadev) if you want.
